### ISSUE TITLE
关于贡献新仓库的流程规范

### ISSUE THREAD

**Issue by LonghronShen** [dotnetcore/Home#1]
为了能帮助更多存量开源.NET项目能继续生存下去，建议我们可以开始讨论贡献仓库的准则和流程。
考虑以下几种情况：
1. 原创项目；
    1.1 已经长肥；
    1.2 有价值的存量项目；
    1.3 社区发起的新坑；
2. 官方项目的fork；
    2.1 官方仓库还在活跃；
    2.2 官方仓库已经长草；

主要的难点是在于项目价值的评价和准入门槛的设置，包括靠谱的代码审查和投票办法的制定；建议增加有孵化器模式，鼓励社区活跃贡献者在社区的官方支持下开新坑。

*可能遇到的特殊情况：*
*如果某个知名的官方仓库并没有明确表示停止维护，但是事实上又存在长期不更新的情况；由于从原则上来说fork一个知名的库是合法的，以社区的名义fork并维护这样的仓库是否合适？*
@alexinea

**Comment by liuhaoyang** [comment]
参考 [加入规范](https://github.com/dotnetcore/Home/blob/master/README.md#%E5%8A%A0%E5%85%A5%E8%A7%84%E8%8C%83)

**Comment by LonghronShen** [comment]
L大真神速

**Comment by liuhaoyang** [comment]
目前的策略还是寻找国内社区优质的开源项目，已自荐或提名的方式加入申请流程。  
对于孵化器，目前NCC没有资金和导师去做，暂且搁置。

**Comment by wu-sheng** [comment]
> 官方项目的fork；
2.1 官方仓库还在活跃；
2.2 官方仓库已经长草；

这个在理论上，需要考虑到license。因为不同的协议，对于二次分发有一些要求的。因为维护fork版本，如果不准备合并，就涉及自己发版的问题。

> 可能遇到的特殊情况：
如果某个知名的官方仓库并没有明确表示停止维护，但是事实上又存在长期不更新的情况；由于从原则上来说fork一个知名的库是合法的，以社区的名义fork并维护这样的仓库是否合适？

按照我的个人经验，在这种情况下，建议不要使用fork库，新建主库，并在readme中的显著位置明确说明。当然前提是对二次分发友好的ASF、MIT协议等。

**Comment by zlzforever** [comment]
@wu-sheng 同意, 可以分两咱情况，只要项目转移到了dotnetcore group的，应该要修改license. 是否允许项目作者自保留所有权，项目又List在dotnet-chine.org中？好像并不冲突

**Comment by LonghronShen** [comment]
所以针对这种情况，比如一些重要的给予MIT协议的一些知名库，如果没人维护的话，可以考虑我们主动发行自己的版本。在以前，这种情况多数是由个人、或者某些企业内部做fork，并没有利用社区的力量。一方面，这些修改没办法让广大开源社区的人一起分享；其次是这些修改也没办法经过大量的验证；最后是，个人或单独某个企业的力量都不够大，最终这些修改很可能被掩埋。
当然这种问题主要针对于上游对PR不感冒的情况。如果上游比较活跃，其实好像也没什么问题，以我们社区的名义提交PR好像也没太大问题的样子？

**Comment by wu-sheng** [comment]
> 是否允许项目作者自保留所有权，项目又List在dotnet-chine.org中？好像并不冲突

我觉得两种方式都不冲突，只是应该明确产权，毕竟很多人（至少在SkyWalking里面）和公司在参与时，对于个人版权是有顾虑的。

**Comment by wu-sheng** [comment]
> 当然这种问题主要针对于上游对PR不感冒的情况。如果上游比较活跃，其实好像也没什么问题，以我们社区的名义提交PR好像也没太大问题的样子？

如果上游活跃，dotnetcore社区官方提供fork库就是比较奇怪的做法了，除非有很大的feature准备集中开发并提供。

但是主流项目，还是比较怕接受大型的pr的。需要提供方构建很多的自动化测试用例。
