### ISSUE TITLE
CanalSharp 申请加入NCC

### ISSUE THREAD

**Issue by stulzq** [dotnetcore/Home#10]
仓库地址：https://github.com/CanalClient/CanalSharp

CanalSharp 是mysql数据库binlog的增量订阅&消费组件 [Canal](https://github.com/alibaba/canal) （阿里巴巴开源项目）的 .NET 客户端。其解决的痛点是，无需使用Java语言去开发应用程序和Canal做对接。

目前正在开发基于事件订阅的使用方式，且使用 DotNetty 进行重构。（[dev-DotNetty 分支](https://github.com/CanalClient/CanalSharp/tree/dev-DotNetty)）

暂定接下来目标：高可用支持（支持Canal集群及CanalSharp主备）、常见的应用场景封装：Redis、Kafka、ElasticSearch等

该项目由我和[XiaoFu](https://github.com/withlin)发起并维护。

**Comment by liuhaoyang** [comment]
+1 
对于.NET Core + Mysql生态完善很有帮助

**Comment by zlzforever** [comment]
+1
非常有用，虽然我还没用起来。可以预见的使用场景非常多，比如开发 MYSQL -> ClickHouse 这样的数据转移工具。

**Comment by fanliang11** [comment]
+1
支持！谢谢无私的付出，完善dotnet生态

**Comment by alexinea** [comment]
+1
非常感谢 @stulzq 与 @XiaoFu 的贡献，该 SDK 对于完善 .net core ecosystem、技术中立性很有助益

**Comment by yang-xiaodong** [comment]
+1
同意，我们目前也在使用 Canal，官方和社区目前还没有 Canal 的 C#客户端，所以这个项目对于生态的完善很有助益

**Comment by xljiulang** [comment]
支持
