### ISSUE TITLE
SmartCode 申请加入 NCC

### ISSUE THREAD

**Issue by Ahoo-Wang** [dotnetcore/Home#11]
SmartCode = IDataSource -> IBuildTask -> IOutput => Build Everything!!!

项目地址：https://github.com/Smart-Kit/SmartCode

**Comment by UtilCore** [comment]
同意加入NCC。
Util代码生成器准备考虑使用SmartCode来做了

**Comment by kiler398** [comment]
同意

**Comment by liuhaoyang** [comment]
+1

**Comment by wangpengxpy** [comment]
+1

**Comment by alexinea** [comment]
SmartCode 是一个非常有意思的代码生成器（同时又不仅仅是一款代码生成器）。

以下是作者提供的 [介绍](https://github.com/Smart-Kit/SmartCode/blob/master/doc/common-problem.md)：

> SmartCode的执行流是 数据源->构建任务->输出，也就是说应用场景非常广泛。
> + 从DB读取数据结构，最终生成整个解决方案=代码生成器（SmartCode.Generator）
> + ETL，其实很显然SmartCode执行流跟ETL很像，做一些相应的扩展便可支持ETL（SmartCode.ETL）
> + Mode First，从Model类结构解析出数据源，最终生成SQL脚本，执行生成DB结构，并生成整个解决方案
> + 静态文档生成器

关于模板：

> 目前SmartCode支持俩种模板引擎 Razor & Handlebars 。 Razor 模板引擎使用的是官方版本，这一点上.NETer同学可以很轻松的自定义SmartCode模板，需要注意的是Razor模板的Model为BuildContext,具体方法可以参考源代码中的模板。编写完成之后放到RazorTemplates，构建时指定好即可。

关于支持的数据库种类：

> SmartCode获取数据源结构使用的是SmartSql，所以SmartCode支持所有ADO.NET驱动相关的数据库：MySql/PostgreSql/SqlServer/Oracle/SQLite 等

关于 SmartCode.ETL：

> [https://www.cnblogs.com/Ahoo-Wang/p/SmartCode-ETL.html](https://github.com/Smart-Kit/SmartCode/blob/master/doc/SmartCode.ETL.md)

**Comment by ElderJames** [comment]
推荐，SmartSql与项目生成器能大大降低有java习惯的开发者尝试.NET Core的学习成本。

**Comment by fanliang11** [comment]
+1

**Comment by zlzforever** [comment]
+1

**Comment by NMSAzulX** [comment]
很好的实现方式，结合了swagger做了暖心的可视化操作。
值得借鉴，为以后系统定制和集成带来了些许灵感，感谢作者。

其他+1
