### ISSUE TITLE
除开源项目之外，是否也可以讨论出一些规范？

### ISSUE THREAD

**Issue by NMSAzulX** [dotnetcore/Home#12]
这里只是举些例子：

例1：  常用Api接口的返回格式，
``` js
{
     code : 0,( 状态码)
     data : {}, (数据)
     warning:string,(警告建议)
     description:string,(描述)
     /*时间戳、分页信息等等...........*/
}
```

例2：企业状态码规范
Long  - >  18位 每一/几位代表什么。

组内优秀的人越来越多，且各位见多识广，汇大家之所学，集大家之所想，打造一些行业规范。

**Comment by alexinea** [comment]
目前 NCC尚没有到达制定标准的水平和地位。
我想即便如日中天如阿里这样的大厂对于标准的输出也是比较谨慎的。

**Comment by yang-xiaodong** [comment]
同意 @alexinea 的看法，我们一般遵循官方或社区约定的代码规范，对于行业规范我想也许还不是时候。

**Comment by zlzforever** [comment]
同意茶的看法

**Comment by NMSAzulX** [comment]
虽然**水平**和**地位**一针见血。
但我还是想挣扎一下，可不可以出草案，在组内人员有条件和机会的条件下，进行实施和演化。

**Comment by zlzforever** [comment]
@NMSAzulX 陈计节老师正在带队做新的.NET 社区网站。可以参与进来打造一个标杆项目，以此为样板供所有.NETer 参考。

**Comment by alexinea** [comment]
项目地址为 https://github.com/jijiechen/dotnetclub/

**Comment by jijiechen** [comment]
不过，如果是有这个方面的考虑，倒不妨先聊一下你的想法？
除了 API 响应格式之外，也许还有别的？@NMSAzulX

**Comment by NMSAzulX** [comment]
@jijiechen 陈大，其他的我暂时还没有想到，目前能接触到的就这些了。 

就是看到阿虎项目的返回格式受点启发。
![12332](https://user-images.githubusercontent.com/16236903/55043861-019c6a80-5073-11e9-9e7a-2b866f500931.png)

**Comment by WeihanLi** [comment]
我觉得每个人的习惯和想法可能都不一样，也没有什么对错之分

我有的项目的返回值是这样的，`Status` 是基于 HTTP Status Code 扩展来的 ，我看陈计节老师的项目里封装了一个 [`ApiResponse`](https://github.com/jijiechen/dotnetclub/blob/dev/src/Discussion.Core/Mvc/ApiResponse.cs#L10) 是直接使用 HttpStatusCode

``` csharp
    /// <summary>
    /// JsonResultModel
    /// </summary>
    /// <typeparam name="T">Type</typeparam>
    public class JsonResultModel<T>
    {
        /// <summary>
        /// JsonResultStatus
        /// </summary>
        public JsonResultStatus Status { get; set; }

        /// <summary>
        /// Message
        /// </summary>
        public string ErrorMsg { get; set; }

        /// <summary>
        /// ResponseData
        /// </summary>
        public T Result { get; set; }

        public void SetSuccessResult(T result)
        {
            ErrorMsg = string.Empty;
            Status = JsonResultStatus.Success;
            Result = result;
        }

        public void SetProcessFailResult()
        {
            ErrorMsg = Resource.InvokeFail;
            Status = JsonResultStatus.ProcessFail;
        }
    }

    /// <summary>
    /// 返回的结果状态
    /// </summary>
    public enum JsonResultStatus
    {
        [Description("Empty Status")]
        None = 0,

        [Description("Continue")]
        Continue = 100,

        [Description("Processing")]
        Processing = 102,

        [Description("Success")]
        Success = 200,

        [Description("Created")]
        Created = 201,

        [Description("BadRequest, Request Parameter Error")]
        RequestError = 400,

        [Description("Unauthorized")]
        Unauthorized = 401,

        [Description("No permission")]
        NoPermission = 403,

        [Description("ResourceNotFound")]
        ResourceNotFound = 404,

        [Description("MethodNotAllowed")]
        MethodNotAllowed = 405,

        [Description("RequestTimeout")]
        RequestTimeout = 408,

        [Description("ProcessFail,Server Internal Error")]
        ProcessFail = 500,

        [Description("ServiceUnavailable")]
        ServiceUnavailable = 503,

        [Description("VersionNotSupported")]
        VersionNotSupported = 505
    }
```

**Comment by zlzforever** [comment]
> @jijiechen 陈大，其他的我暂时还没有想到，目前能接触到的就这些了。
> 
> 就是看到阿虎项目的返回格式受点启发。
> ![12332](https://user-images.githubusercontent.com/16236903/55043861-019c6a80-5073-11e9-9e7a-2b866f500931.png)

没有银弹。可以参考这本书 <<Web API的设计与开发>> 。按照阿里的说法，它们的JSON字段不会用isXXX 这种，因为 JAVA 里 bool 类型的属性的 get 方法是 isXXX()

**Comment by zlzforever** [comment]
> 我觉得每个人的习惯和想法可能都不一样，也没有什么对错之分
> 
> 我有的项目的返回值是这样的，`Status` 是基于 HTTP Status Code 扩展来的 ，我看陈计节老师的项目里封装了一个 [`ApiResponse`](https://github.com/jijiechen/dotnetclub/blob/dev/src/Discussion.Core/Mvc/ApiResponse.cs#L10) 是直接使用 HttpStatusCode
> 
> ```cs
>     /// <summary>
>     /// JsonResultModel
>     /// </summary>
>     /// <typeparam name="T">Type</typeparam>
>     public class JsonResultModel<T>
>     {
>         /// <summary>
>         /// JsonResultStatus
>         /// </summary>
>         public JsonResultStatus Status { get; set; }
> 
>         /// <summary>
>         /// Message
>         /// </summary>
>         public string ErrorMsg { get; set; }
> 
>         /// <summary>
>         /// ResponseData
>         /// </summary>
>         public T Result { get; set; }
> 
>         public void SetSuccessResult(T result)
>         {
>             ErrorMsg = string.Empty;
>             Status = JsonResultStatus.Success;
>             Result = result;
>         }
> 
>         public void SetProcessFailResult()
>         {
>             ErrorMsg = Resource.InvokeFail;
>             Status = JsonResultStatus.ProcessFail;
>         }
>     }
> 
>     /// <summary>
>     /// 返回的结果状态
>     /// </summary>
>     public enum JsonResultStatus
>     {
>         [Description("Empty Status")]
>         None = 0,
> 
>         [Description("Continue")]
>         Continue = 100,
> 
>         [Description("Processing")]
>         Processing = 102,
> 
>         [Description("Success")]
>         Success = 200,
> 
>         [Description("Created")]
>         Created = 201,
> 
>         [Description("BadRequest, Request Parameter Error")]
>         RequestError = 400,
> 
>         [Description("Unauthorized")]
>         Unauthorized = 401,
> 
>         [Description("No permission")]
>         NoPermission = 403,
> 
>         [Description("ResourceNotFound")]
>         ResourceNotFound = 404,
> 
>         [Description("MethodNotAllowed")]
>         MethodNotAllowed = 405,
> 
>         [Description("RequestTimeout")]
>         RequestTimeout = 408,
> 
>         [Description("ProcessFail,Server Internal Error")]
>         ProcessFail = 500,
> 
>         [Description("ServiceUnavailable")]
>         ServiceUnavailable = 503,
> 
>         [Description("VersionNotSupported")]
>         VersionNotSupported = 505
>     }
> ```

按照<<Web API的设计与开发>>书中所说，要遵守HTTP的规范，如果是404就应该返回404，不要所有接口都返回200，自己在消息体里定义状态码。这样不同客户端，平台会有较好的兼容性。

**Comment by WeihanLi** [comment]
> > 我觉得每个人的习惯和想法可能都不一样，也没有什么对错之分
> > 我有的项目的返回值是这样的，`Status` 是基于 HTTP Status Code 扩展来的 ，我看陈计节老师的项目里封装了一个 [`ApiResponse`](https://github.com/jijiechen/dotnetclub/blob/dev/src/Discussion.Core/Mvc/ApiResponse.cs#L10) 是直接使用 HttpStatusCode
> > ```cs
> >     /// <summary>
> >     /// JsonResultModel
> >     /// </summary>
> >     /// <typeparam name="T">Type</typeparam>
> >     public class JsonResultModel<T>
> >     {
> >         /// <summary>
> >         /// JsonResultStatus
> >         /// </summary>
> >         public JsonResultStatus Status { get; set; }
> > 
> >         /// <summary>
> >         /// Message
> >         /// </summary>
> >         public string ErrorMsg { get; set; }
> > 
> >         /// <summary>
> >         /// ResponseData
> >         /// </summary>
> >         public T Result { get; set; }
> > 
> >         public void SetSuccessResult(T result)
> >         {
> >             ErrorMsg = string.Empty;
> >             Status = JsonResultStatus.Success;
> >             Result = result;
> >         }
> > 
> >         public void SetProcessFailResult()
> >         {
> >             ErrorMsg = Resource.InvokeFail;
> >             Status = JsonResultStatus.ProcessFail;
> >         }
> >     }
> > 
> >     /// <summary>
> >     /// 返回的结果状态
> >     /// </summary>
> >     public enum JsonResultStatus
> >     {
> >         [Description("Empty Status")]
> >         None = 0,
> > 
> >         [Description("Continue")]
> >         Continue = 100,
> > 
> >         [Description("Processing")]
> >         Processing = 102,
> > 
> >         [Description("Success")]
> >         Success = 200,
> > 
> >         [Description("Created")]
> >         Created = 201,
> > 
> >         [Description("BadRequest, Request Parameter Error")]
> >         RequestError = 400,
> > 
> >         [Description("Unauthorized")]
> >         Unauthorized = 401,
> > 
> >         [Description("No permission")]
> >         NoPermission = 403,
> > 
> >         [Description("ResourceNotFound")]
> >         ResourceNotFound = 404,
> > 
> >         [Description("MethodNotAllowed")]
> >         MethodNotAllowed = 405,
> > 
> >         [Description("RequestTimeout")]
> >         RequestTimeout = 408,
> > 
> >         [Description("ProcessFail,Server Internal Error")]
> >         ProcessFail = 500,
> > 
> >         [Description("ServiceUnavailable")]
> >         ServiceUnavailable = 503,
> > 
> >         [Description("VersionNotSupported")]
> >         VersionNotSupported = 505
> >     }
> > ```
> 
> 按照<<Web API的设计与开发>>书中所说，要遵守HTTP的规范，如果是404就应该返回404，不要所有接口都返回200，自己在消息体里定义状态码。这样不同客户端，平台会有较好的兼容性。

嗯，受教了，最初这个只是给一个 mvc 的应用定义的，没有考虑 api，api 应用的话陈计节老师这种方式我觉得挺不错的

**Comment by jijiechen** [comment]
这个东西也是一个矛盾体。
REST 确实把状态码当作一种状态信息，也就是说它代表一种“业务状态”。

但矛盾在于，假如 404 用于表示一个业务对象不存在，又用什么来表示请求的 URL 不存在呢？
现实生活中，有几个情况，让我们不得不思考这个思想应该如何实践：

- 此外，很多客户端框架把 200~399 之外的状态码（请求正常）默认认为是请求失败，会调用相关的 Error Handling 机制。
- 同时，.NET、Java 这些客户端通常会在服务器返回非正常状态码时，抛出异常，客户端需要在一个“更低级封装层次”的位置做额外处理。
- 由于浏览器和监控器通常把非正常状态码标记为红色、统计为错误，测试人员一般也认为这是错误，会比较紧张（虽然可以人工安抚）

实际开发中种种这些因素，让我对使用状态码表述业务状态有了一些动摇。

**Comment by alexinea** [comment]
以前在开发支付功能的时候，能发现支付网关的返回结果一般至少分2种类型的返回码：技术级的返回编码和业务级的返回编码。我觉得在实践当中，这种分类型的返回编码要比RESTful的标准更贴近实践。

比如一个业务对象存不存在，但接口本身是调用成功的，那么HTTP状态码返回200、在业务码中体现「对象不存在」是比较合理的。

**Comment by NMSAzulX** [comment]
+1，鄙人之前的项目，ajax是要根据http的状态码进行回调的，而业务编码是作为内容返回的。
