### ISSUE TITLE
SmartSql 申请加入 NCC

### ISSUE THREAD

**Issue by Ahoo-Wang** [dotnetcore/Home#14]
SmartSql = MyBatis + Cache(Memory | Redis) + R/W Splitting +Dynamic Repository + Diagnostics ......

项目地址：https://github.com/Smart-Kit/SmartSql

**Comment by UtilCore** [comment]
同意

**Comment by alexinea** [comment]
赞同加入。
非常期待这款能对标 [MyBatis-Plus](https://mybatis.plus/) 的优秀项目在实现 2019 roadmap 后再向前迈出一大步。

**Comment by fanliang11** [comment]
感谢对开源社区的贡献！同意+1

**Comment by geffzhang** [comment]
同意

**Comment by yang-xiaodong** [comment]
同意

**Comment by ElderJames** [comment]
赞同加入。
唯一能在能与Mybatis对标的.NET ORM。性能上与Dapper媲美，但又比Dapper强大很多。值得推荐！
