### ISSUE TITLE
FlubuCore applies to join NCC

### ISSUE THREAD

**Issue by mzorec** [dotnetcore/Home#15]
Project description: "FlubuCore - Fluent Builder Core" is a cross platform build and deployment automation system. You can define your build and deployment scripts in C# using an intuitive fluent interface. This gives you code completion, IntelliSense, debugging, FlubuCore custom analyzers, and native access to the whole .NET ecosystem inside of your scripts.

Project's GitHub repository url: https://github.com/flubu-core/flubu.core

Project's document/wiki: https://github.com/flubu-core/flubu.core/wiki

Author and core contributors' info: 
https://github.com/orgs/flubu-core/people/mzorec 
https://github.com/orgs/flubu-core/people/zoroz

License: BSD 2-Clause

**Comment by mzorec** [comment]
Is this community only for china? If that's the case you should probably mention this in project requirements for joining NCC

**Comment by alexinea** [comment]
Since these days are China's national holidays, no one has ever dealt with this issue.
I will assign this application to the members of the committee..

**Comment by UtilCore** [comment]
欢迎国外的项目加入NCC.

**Comment by UtilCore** [comment]
同意

**Comment by jijiechen** [comment]
@mzorec  Thanks for the application and the idea of creating build scripts using C#. 
I do not have concerns on this application, so it is approved from me. This project has two core contributors and a couple of related projects. I believe it will be well developed in the near future.

I'm a little curious about what do you think is the advantage in comparison to [CakeBuild](https://cakebuild.net/), since you even build a bridge for FlubuCore to leverage CaseBuild's plugins.

**Comment by fanliang11** [comment]
Thanks for contributing to the .NET community and joining NCC, it would be great if you could add responsive programming.

**Comment by xingwen1987** [comment]
Thanks for contributing to the .NET community and joining NCC！We will conduct group discussions, code review and so on.

**Comment by mzorec** [comment]
@jijiechen 

Couple of main adventages that I see are:

- The *.cake files aren't valid C# files. That means that cake runner must interpret them, dynamically compile them, and then execute them. When you do this, you loose support for the standard toolchain (dotnet), and built in IDE support. FlubuCore integrates as normal C# project, meaning all the basic IDE features like auto-completion, navigation, debugging and refactorings are available out of the box.
- In my opinion better designed API.
- Auto generated API for some third party command-line tools like docker.
- Parameter injection, which supports command-line arguments, json configuration files, and environment variables
- Posibility to execute scripts remotely via the FlubuCore Web API. Useful for executing deployment scripts.

**Comment by alexinea** [comment]
FlubuCore is such a wonderful project and I am very happy that it conforms to all NCC's application requirements, preliminary review completed. After entering the technical review phase, we will randomly assign 5 members (including Microsoft MVP and Tencent Cloud TVP experts).

**Comment by geffzhang** [comment]
Welcome  you join NCC, I'm agree.

**Comment by yang-xiaodong** [comment]
Hello @mzorec，

Thank you for applying to join NCC, I think FlubuCore is grate tools for building and deploying in .NET.

I've spent hours studying and learning about it, it's very simple and easy to use, especially for.net Framework applications, which greatly simplifies the use of CI tools for deployment and publishing and is familiar with C# code. It has many advantages over using MSBuild or Cake directly, such as it encapsulates many very useful functions and operations

I think this must be of great value to the construction of the .NET ecosystem, and I absolutely agree to join us.

I have a question about that Flubu is currently under the flubu-core organization, what should other related projects do during the migration process like `FlubuCore.CakePlugin`, `examples` and so on?

**Comment by mzorec** [comment]
I am glad that you all like Flubu and find it useful. Hope we can make it even better together.

**Comment by NMSAzulX** [comment]
Welcome you join NCC, I'm agree.

**Comment by ElderJames** [comment]
Welcome！

**Comment by EdiWang** [comment]
I'm impressed. Welcome to join NCC!

**Comment by NMSAzulX** [comment]
@mzorec  Welcome to our room.  [https://gitter.im/dotnetcore/community ](https://gitter.im/dotnetcore/community ) We can communicate inside.
