### ISSUE TITLE
MSTestEnhancer 申请加入 NCC 

### ISSUE THREAD

**Issue by lindexi** [dotnetcore/Home#16]
MSTestEnhancer 是一个单元测试框架，用于解决程序员写单元测试的命名问题

我的团队大多数的小伙伴的英文水平都比较低，如果遵守单元测试的命名规范写，那么写出来的单元测试的方法名他自己都读不懂。在鼓励小伙伴写单元测试的时候，就做了 MSTestEnhancer 通过中文分割单元测试

可以写出下面的代码

[TestClass]
```
public class DemoTest
{
    [ContractTestCase]
    public void Foo()
    {
        "当满足 A 条件时，应该发生 A' 事。".Test(() =>
        {
            // Arrange
            // Action
            // Assert
        });
        
        "当满足 B 条件时，应该发生 B' 事。".Test(() =>
        {
            // Arrange
            // Action
            // Assert
        });
    }
}
```

运行单元测试可以看到下图

![](https://github.com/dotnet-campus/MSTestEnhancer/blob/master/docs/images/unit-test-result-of-demo.zh-chs.png)

项目地址：https://github.com/dotnet-campus/MSTestEnhancer

**Comment by Ahoo-Wang** [comment]
1. 如果是因为语言的问题长久考虑或许尝试提高团队英文水平更好，至少可以先使用翻译器。
2. 比如 Xunit 使用 FactAttribute.DisplayName 属性注解 来解决显示问题的。当然更加建议的是良好的命名规范，使用 DisplayName 作为辅助而已。
3. 样例中单个测试函数里边编写俩个条件单元测试，这应该不是好的实践。
4. 该项目最后一次commit日期是 2018-06-21 ,对该项目的活跃度表示担心。
5. 感谢作者对开源的贡献。

反对。

**Comment by NMSAzulX** [comment]
**首先感谢作者的贡献**

大致看了一下，我提出几条建议：

1. 考虑一下如何让大家参与到你的项目中，如果编译环境复杂最好在readme里做出说明。
2. MD文档，从源地址截图中看到结果，貌似缺少耗时计数，最好给出不同指标的案例截图。
3. 侵入性角度，从3个测试框架来看，XUnit是比较合适的。
4. 看到对object进行反射扩展的时候，采用了GetValue和SetValue等低性能反射方法，建议改进。
5. 看到还有些其他扩展，如果你扩展的测试功能涵盖了标准库中的本身就具备的功能，这个行为有些敏感。详见 [StringAssertExtensions](https://github.com/dotnet-campus/MSTestEnhancer/blob/b5de5de01595bd5a9afe37db2cf9f871fbfdd2e3/src/MSTest.Extensions/AssertExtensions/StringAssertExtensions.cs#L59) 等

我持反对意见，也悉听大神们的意见。

**Comment by alexinea** [comment]
MSTestEnhancer 项目没有达到以下[申请标准](https://github.com/dotnetcore/Home/blob/master/docs/rules/project-requirements-for-joining-ncc.md)：
+ 第6点【项目作者或核心贡献者在最近一个月内（申请日（含）向前的 30 天）对项目有贡献；】
+ 第7点【项目的仓库（官档优先为 GitHub）至少拥有 50 颗星（star）；】

因此 MSTestEnhancer 项目未能通过 NCC 初步评审 环节。

请继续加油 💪

**Comment by lindexi** [comment]
好的，继续渣油
