### ISSUE TITLE
推荐潜力项目 KoobooJson 进入NCC

### ISSUE THREAD

**Issue by NMSAzulX** [dotnetcore/Home#21]
https://github.com/Kooboo/Json

此项目为高性能Json序列化项目：  

1、入组条件基本符合
2、项目类型处理完整，考虑的比较充分
3、有较完整的UT测试
4、优化效果明显，算法值得回味，跑分靠前
5、中英文readme齐全
6、星数超过半百

个人感觉前景较好，推荐进入NCC内孵化，请各位审查。

**Comment by liuhaoyang** [comment]
该项目的roadmap？以及如何处理和json.net的关系

**Comment by yang-xiaodong** [comment]
这个库我之前测试过，和 json.net 比起来缺失一些功能，另外比如基本的带构造函数的反序列化都不能正确序列化成功，我觉得还需要进一步考察。

**Comment by fanliang11** [comment]
该项目有JObject, JArray 这相似的类型吗？还有该项目能支持JsonPath 解析吗？比如以下代码 
‘’‘ c#
          var jsonobject = new JObject();
            var values = jsonobject.SelectTokens("Surging.Packages[?(@.TypeName == 'EnginePartModule')].Using") 
            .Select(v => (string)v) 
            .FirstOrDefault();
’‘’

**Comment by zlzforever** [comment]
@fanliang11 想支持 json path ，性能就不太可能快了

**Comment by xljiulang** [comment]
目前WebApiClient是基于Json.net来实现json和表单的序列化，深入json.net发现其特性灵活，已经是一个接近完美的。另外,system.text.json也要出来了，其慢慢增加和json.net类似的开放性功能，根正苗红，所以我个人感觉Kooboojson的路子太遥远。

**Comment by 1996v** [comment]
> 该项目的路线图？以及如何处理和json.net的关系

你好, kooboojson定位于 小巧，快速，以及在维持这两个特点上所折中带来的的特性多样化。
它与json.net的定位不同。json.net是一个非常全面，体系及兼容性非常强大的库，它的多样性也带来了一些不可避免的因素，因为要维持一些兼容和其它方面的特性，所以json.net中的代码并不是以性能为衷的，与一款以性能为主的json框架，这直接的差异还是很明显的，当然，性能并不是json.net所追求的，也是为了保持.net体系中各种发展及遗留问题也不能追求的。另一方面，就是库的体积大小方面，json.net相对来说较为庞大。
那么，kooboojson如何？
每一款框架的诞生，大部分都是因为有一个必要的点，当你为了考虑应用程序(这里不是指服务端)的体积大小，又要考虑到一些热点代码路径上的序列化性能时，你会发现这些要求在.net中所选范围非常小。当然，也不是没有，如性能界中最出名的JIL，UTF-8JSON，这样知名且优异的JSON框架。
那么，我为什么不选择它们？
体积和依赖，这两个库有一些依赖条件，这意味着在某些版本(场景)我不能直接"开箱即用"，另一方面，因为有一些预处理的手段，所以体积也相对之大。
所以，我决定写kooboojson。
kooboojson的体积目前在200k之内，相较之非常轻量，没有任何依赖。而还要值得一提的就是，在性能上的追求和选择方面，我的实现和他们的不同，当前主流的直接实现是EMIT技术，但是这种技术相对来说，维护体系较为复杂，而kooboojson另一个出发点是可以让更多的人来参与扩展和维护，所以采用的技术是表达式树。
在动态技术上，表达式树依赖于下层的clr库中的解析器，而emit则是直接生成中间码，所以较之性能上的比较上来说，emit当然性能要强于表达式树，但是差异有限。不过kooboojson在代码上运用了一些小技巧，如热点分支的分支预测，调用路径更少的json读取器，预处理的自动机匹配算法，加速的字节比较技术...这让kooboojson在于jil和utf-8json之间的性能比较中略胜一筹。
那么，扩展功能的多样性如何？
kooboojson实现了和jil,utf-8json一致的特性功能，因为是侧重于性能，所以和Json.net在特性上比不了，在性能和特性中有所取舍。
那么，我该怎样说服你用kooboojson？
当你做客户端时需要一个比较小的json库时，当你需要一个非常强劲性能的序列化工具时，当你需要一定的特性支持时(目前15个特性)，当你需要二次开发时(代码结构清晰，且表达式树易于维护)，你需要kooboojson!


kooboojson的未来
kooboojson将仍然追求小巧，性能，同时仍然会在保证这两点之上，去增加用户提出来的特性点。并且我也会经常在社区宣传开源项目，致力于结交那些敢于开源，敢于奉献精神的朋友们。

最后，我会听取各位对我的意见，期待进入NCC。
感谢

**Comment by 1996v** [comment]
> 这个库我之前测试过，和json.net比起来缺失一些功能，另外比如基本的带构造函数的反序列化都不能正确序列化成功，我觉得还需要进一步考察。

你好，能不能给出示例，项目已经线上真实环境运行良久，目前没有发现过任何问题。

**Comment by 1996v** [comment]
> JObject，JArray

有JObject，JArray，但不支持JsonPath

**Comment by 1996v** [comment]
> 目前WebApiClient是基于Json.net来实现JSON和表单的序列化，深入json.net发现其特性灵活，已经是一个接近完美的。另外，system.text.json也要出来了，其慢慢增加和JSON .NET类似的开放性功能，根正苗红，所以我个人感觉Kooboojson的路子太遥远。

你好，kooboojson的定位与之不同，如果不考虑应用程序体积大小和序列化性能的话，确实在项目中没必要选择kooboojson

**Comment by 303248153** [comment]
程序体积大小：System.Text.Json SDK内置，不需要安装第三方 nuget 包
序列化性能：System.Text.Json 支持直接序列化与反序列化 bytes，使用 span 减少分配，性能会超越目前所有的 .net json 类库
支持进入 NCC 但是不感觉有人会用 🐶

**Comment by 1996v** [comment]
> 程序体积大小：System.Text.Json SDK内置，不需要安装第三方 nuget 包
> 序列化性能：System.Text.Json 支持直接序列化与反序列化 bytes，使用 span 减少分配，性能会超越目前所有的 .net json 类库
> 支持进入 NCC 但是不感觉有人会用 🐶

你好，不对哟，sdk内置的前提是系统得有这个sdk库，但是System.Text.Json肯定是后面的net版本库中才会发布，对于只有net fx或者net core2x 的系统而言，仍然要单独引用新的nuget包，那么作为原生的sdk库，其为了保存兼容性和多样性，这个体积我觉得应该会超300k.
另外span只是对指针的包装，在kooboojson中，为了提高性能，很多细致操作都使用了指针。但是在序列化工具中，决定性能差异的并不是取决于几十byte的这块小内存分配上(因为大对像的池技术每个库都有)，而是取决于动态生成技术所带来的差异，无需装箱拆箱，更容易内联，无需键值查找，更快的预处理机制等等...我认为System.Text.Json应该不会使用动态生成技术，因为作为一个sdk库，它的定位应该在于兼容和扩展，动态技术只会让其变得更复杂。

**Comment by zlzforever** [comment]
这个实现挺有意思的，**我支持进入**。就是感觉使用的人会有限，我做一个第三方库的选型不太会考虑包的大小，主要侧重性能、稳定性、使用的人多不多、资料多不多等。不考虑性能 json.net 的功能非常完善并且它的性能在大部分情况下是够用的。考虑性能有jil, system.text.json, 甚至不使用json(messagepack, protobuf, thrif）等其它序列化手段。

**Comment by liuhaoyang** [comment]
> 这个实现挺有意思的，**我支持进入**。就是感觉使用的人会有限，我做一个第三方库的选型不太会考虑包的大小，主要侧重性能、稳定性、使用的人多不多、资料多不多等。不考虑性能 json.net 的功能非常完善并且它的性能在大部分情况下是够用的。考虑性能有jil, system.text.json, 甚至不使用json(messagepack, protobuf, thrif）等其它序列化手段。

+1 可以进入孵化器

**Comment by catcherwong** [comment]
支持进入孵化器
