### ISSUE TITLE
Magicodes.IE申请加入NCC

### ISSUE THREAD

**Issue by xin-lai** [dotnetcore/Home#26]
项目描述:
导入导出通用库，通过导入导出DTO模型来控制导入和导出，支持Excel、Word、Pdf和Html。

项目官档（GitHub）地址:
项目官网地址:
项目文档/Wiki 的地址:
https://github.com/xin-lai/Magicodes.IE

作者和核心贡献者信息:

- 李文强（博客园雪雁，https://www.cnblogs.com/codelove/）
- 代瓒
- 张善友

许可证：MIT

**Comment by geffzhang** [comment]
这个库好用哦，我贡献了几百行代码

**Comment by 303248153** [comment]
支持，这个库很实用 😄

**Comment by NMSAzulX** [comment]
麻烦把首页的Demo修复一下，我想跑起来试试。
![image](https://user-images.githubusercontent.com/16236903/69696887-03e02880-111c-11ea-911d-c9d191a69d67.png)

**Comment by xin-lai** [comment]
@NMSAzulX 上午更新了下抬头，Reshaper清理之后出问题了。刚修复提交了。

**Comment by NMSAzulX** [comment]
我用Natasha在动态环境中测试了一下：
 - 隔离域环境可以操作
-  可在运行时动态定制类结合该库导出数据较方便
-  局限：该库目前应该仅支持属性操作
![image](https://user-images.githubusercontent.com/16236903/69699078-03e32700-1122-11ea-9615-63aac0a140c7.png)

![image](https://user-images.githubusercontent.com/16236903/69698872-6d166a80-1121-11ea-842d-a6d0cae7124d.png)

**Comment by NMSAzulX** [comment]
@xin-lai  目前除了单表之外，支持多维操作吗？

**Comment by xin-lai** [comment]
@NMSAzulX 
设计理念就是围绕Dto来进行导入导出的，今天会写个导入的文档案例出来，到时发你看看可能就理解我们的设计目的了。
多维操作后续会支持。

**Comment by NMSAzulX** [comment]
@xin-lai 辛苦，期望后面有更强大的功能出现。 

支持，同意。

**Comment by xin-lai** [comment]
@NMSAzulX 需要实现的内容还很多，思路都有，就是目前在创业关键阶段，精力和时间非常有限，希望一起来驱动。

**Comment by xin-lai** [comment]
@NMSAzulX 
[基础教程之导入学生数据](https://github.com/xin-lai/Magicodes.IE/blob/master/docs/1.%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B%E4%B9%8B%E5%AF%BC%E5%85%A5%E5%AD%A6%E7%94%9F%E6%95%B0%E6%8D%AE.md)

**Comment by NMSAzulX** [comment]
> @NMSAzulX
> [基础教程之导入学生数据](https://github.com/xin-lai/Magicodes.IE/blob/master/docs/1.%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B%E4%B9%8B%E5%AF%BC%E5%85%A5%E5%AD%A6%E7%94%9F%E6%95%B0%E6%8D%AE.md)

例子通俗易懂，单表情况几乎覆盖全了。

**Comment by alexinea** [comment]
The **Standard Review** is done by Tommy (套总), an independent reviewer authorized by the NCC Project Management Committee. The review result is "Passed Review".

根据独立评审员套总（Tommy）的评审结果，本项目通过「初步评审」环节。

**Comment by xin-lai** [comment]
收到。感谢各位！！

**Comment by alexinea** [comment]
赞同加入

**Comment by UtilCore** [comment]
赞同加入

**Comment by xljiulang** [comment]
同意加入

**Comment by jijiechen** [comment]
同意加入
