### ISSUE TITLE
ButterflyAPM加入NCC申请

### ISSUE THREAD

**Issue by liuhaoyang** [dotnetcore/Home#3]
ButterflyAPM是使用.NET Core开发并适用于.NET Core平台的分布式追踪和应用性能监控项目。项目地址：https://github.com/ButterflyAPM
- Buttefly现包含三个子项目
   - [butterfly server](https://github.com/ButterflyAPM/butterfly) APM Collector项目
   - [butterfly .net core client](https://github.com/ButterflyAPM/butterfly-csharp)
   - [butterfly-ui](https://github.com/ButterflyAPM/butterfly-ui)
- 开源协议 [MIT](https://github.com/ButterflyAPM/butterfly/blob/master/LICENSE)
- 使用案例 [Ocelot](https://github.com/ThreeMammals/Ocelot)

@alexinea @yuleyule66 @UtilCore

**Comment by jack2gs** [comment]
赞成

**Comment by catcherwong** [comment]
赞成

**Comment by seayxu** [comment]
赞成

**Comment by yuleyule66** [comment]
赞成

**Comment by Dason1986** [comment]
赞成

**Comment by stulzq** [comment]
赞成

**Comment by lanyan0216** [comment]
赞成

**Comment by xljiulang** [comment]
赞成

**Comment by geffzhang** [comment]
赞成

**Comment by fanliang11** [comment]
赞成

**Comment by heyixiaoran** [comment]
赞成

**Comment by ChujianA** [comment]
赞成

**Comment by MrZc** [comment]
赞成
