### ISSUE TITLE
osharp申请加入NNC

### ISSUE THREAD

**Issue by gmf520** [dotnetcore/Home#30]
- 名称：OSharp 快速开发框架
- 描述：OSharpNS 全称 OSharp Framework with .NetStandard2.x，前身 .net fx 版本始创于2014年，现在的.net core版本是一个基于.NetStandard2.x开发的一个.NetCore快速开发框架。这个框架使用最新稳定版的.NetCore SDK（当前是.NET Core 3.1），对 AspNetCore 的配置、依赖注入、日志、缓存、实体框架、Mvc(WebApi)、身份认证、权限授权等模块进行更高一级的自动化封装，并规范了一套业务实现的代码结构与操作流程，使 .Net Core 框架更易于应用到实际项目开发中。
- 项目官档（主要是 GitHub）的地址：https://github.com/i66soft/osharp
- 文档或 Wiki 地址：https://docs.osharp.org/
- 官方网站地址：https://www.osharp.org/
- 作者及核心贡献者信息：@gmf520
- 许可证情况：[![GitHub license](https://img.shields.io/badge/license-Apache%202-blue.svg)](https://raw.githubusercontent.com/i66soft/osharp-ns20/master/LICENSE)

**Comment by liuhaoyang** [comment]
赞成 +1

**Comment by xin-lai** [comment]
赞成++

**Comment by ElderJames** [comment]
+1

**Comment by kiler398** [comment]
赞成 +1

**Comment by Ahoo-Wang** [comment]
赞成 +1

**Comment by zlzforever** [comment]
+1 之前阅读过，功能还是很完善的

**Comment by catcherwong** [comment]
+1，很不错的快速开发框架

**Comment by UtilCore** [comment]
同意

**Comment by NMSAzulX** [comment]
同意

**Comment by alexinea** [comment]
赞同。
