### ISSUE TITLE
ant-design-blazor 申请加入

### ISSUE THREAD

**Issue by lindexi** [dotnetcore/Home#31]
- 名称： Ant Design Blazor
- 描述：基于 Ant Design 和 Blazor 的企业级组件库
- 项目官档（主要是 GitHub）的地址：https://github.com/ElderJames/ant-design-blazor
- 作者及核心贡献者信息：https://github.com/ElderJames
- 许可证情况：[![AntBlazor](https://img.shields.io/badge/License-MIT-blue?style=flat-square)](https://github.com/ElderJames/ant-design-blazor/blob/master/LICENSE)

**Comment by alexinea** [comment]
The project application needs to be led by the project leader (including the author, the team leader of the team, and the main person in charge of the enterprise project).

Therefore this application is invalid.
