### ISSUE TITLE
Blazui 申请加入NCC

### ISSUE THREAD

**Issue by lindexi** [dotnetcore/Home#32]
- 名称： Blazui 
- 描述：Element的blazor版本，用 .NET 写前端的 UI 框架，无JS，无TS，非 Silverlight，非 WebForm，开箱即用
- 项目官档（主要是 GitHub）的地址：https://github.com/wzxinchen/Blazui
- 作者及核心贡献者信息：@wzxinchen
- 许可证情况：![](https://img.shields.io/badge/License-MIT-blue?style=flat-square)

**Comment by alexinea** [comment]
The project application needs to be submitted by the project leader (including the author, the team leader of the team, and the main person in charge of the enterprise project).

Therefore this application is invalid.
