### ISSUE TITLE
OpenAuth.Core申请加入NCC

### ISSUE THREAD

**Issue by yubaolee** [dotnetcore/Home#33]
名称：OpenAuth.Core
描述：OpenAuth.Core是一套基于.Net Core快速应用开发框架，最新版采用.net core sdk 3.1.100。核心功能为权限管理、工作流功能开发。其中：

- 权限管理已实现：模块权限、菜单权限、数据权限；
- 工作流已实现：普通审批、会签、条件分支；

技术方面，主要涉及AutoFac、Swagger、IdentityServer 4、EF、LayUI、vue等
项目地址：

- https://gitee.com/yubaolee/OpenAuth.Core
- https://github.com/yubaolee/OpenAuth.Core

文档或 Wiki 地址：http://doc.openauth.me/
官方网站地址：http://openauth.me/
作者及核心贡献者信息：@yubaolee
许可证情况：LGPL

---

*Alex Lewis 补充 <sup>(2020-04-13)</sup>：*

- *根据「关于申请加入 NCC 的项目的规定（2019）」，项目的许可证调整为 Apache 2.0 License*
- *根据「社区商业阻隔条例（2019）」，项目 README 已移除非社区版本的说明信息*

**Comment by 2881099** [comment]
商业版 998元？

**Comment by 2881099** [comment]
![0AF22341-2E8F-4F77-AD8E-367406FFB750](https://user-images.githubusercontent.com/16286519/79085322-b67ef380-7d6a-11ea-828b-d1b3c533faeb.png)

**Comment by ElderJames** [comment]
+1，希望作者可以把主要开发仓库转到 Github，让 NCC 社区更活跃。

**Comment by yang-xiaodong** [comment]
@ALL 由于该项目涉及商业资源，所以大家评审的时候注意下社区版和商业版代码的功能的区分，以及对应的代码范围。 
理论上社区版和商业版仅应存在技术支持和非必要功能的支持的区别，也就是确保社区版功能是完整的

**Comment by ElderJames** [comment]
对，还需要考虑社区版本的后期维护和功能更新是否可持续。

**Comment by NMSAzulX** [comment]
作者很用心，很好很强大，会持续关注。 数据从录入，到分配，到审批，到展示，及全程的权限变更，可以提供一个完整的案例？

**Comment by gmf520** [comment]
下载代码看了下，有几个感受分享下：
1. UI漂亮
2. 数据权限的实现跟 osharp 类似，有共鸣
3. .net core3.x+，Microsoft.AspNetCore引用可以去掉了
4. 代码和UT混在一起，导致项目无关依赖项太多太杂，建议分开
5. 不知定位是什么，作为一个组件，感觉很难用到现有项目中，作为一个开发框架，又显得不够，不易扩展

**Comment by yubaolee** [comment]
@2881099 
已移除该图片

> @ALL 由于该项目涉及商业资源，所以大家评审的时候注意下社区版和商业版代码的功能的区分，以及对应的代码范围。
> 理论上社区版和商业版仅应存在技术支持和非必要功能的支持的区别，也就是确保社区版功能是完整的

商业版是完全独立的前端界面，使用的是社区版接口项目，开源版本保证完整功能和代码开源！整体结构如下：
![Architect](http://pj.openauth.me/zentao/file-read-70.png)

**Comment by yubaolee** [comment]
@gmf520 
感谢
针对你提出的以下两点：
4 尽快做UT的分离
5 目前定位为开发框架，会在扩展性和易用性上努力。
