### ISSUE TITLE
 需搭建多语言混合架构社区，请求分化出去发展

### ISSUE THREAD

**Issue by fanliang11** [dotnetcore/Home#34]
因为surging发展需要,需要分化独立发展形成完整的生态链社区. 有几大设想。
1.多语言生态组建。
2. 中间件生态。
3.官方站建立
4.后续发展商业化支持
也希望得到社区的支持，同意能分化出来独立发展。

**Comment by Ahoo-Wang** [comment]
同意

**Comment by NMSAzulX** [comment]
支持，同意

**Comment by alexinea** [comment]
Authorized by NCC-CC and voted by NCC PMC. After getting approval from more than 2/3 members, Surging is now leaving NCC and setting up its own community.

**Comment by zlzforever** [comment]
支持，同意

**Comment by liuliang-wt** [comment]
支持

**Comment by 2881099** [comment]
支持

**Comment by fanliang11** [comment]
感谢NCC的孵化，也祝NCC发展越来越好
