### ISSUE TITLE
HttpReports 申请加入NCC

### ISSUE THREAD

**Issue by SpringLeee** [dotnetcore/Home#35]
HttpReports 是针对.Net Core 开发的轻量级APM系统，基于MIT开源协议, 使用HttpReports可以快速搭建.Net Core环境下统计,分析,图表,监控，分布式追踪一体化的站点， 适应.Net Core WebAPI,MVC，Web项目, 通过引用Nuget构建Dashboard面板，上手简单，适合在微服务架构中使用。

Github地址：https://github.com/SpringLeee/HttpReports

在线预览： https://moa.hengyinfs.com

账号: admin 密码 123456

**Comment by NMSAzulX** [comment]
你好，后面的计划或者roadmap有吗？想看一下。

**Comment by NMSAzulX** [comment]
按错了，不好意思，这个项目我个人觉得功能单一，但却是潜力项目，后面的更新计划或者roadmap有吗？

**Comment by SpringLeee** [comment]
后边更新的主要更新以下几点：

- CLR 监控
- 数据库SQL 监控
- 服务健康发现
- 收集考虑使用 SkyAPMdotnet 的探针收集方式

**Comment by mzorec** [comment]
- Just wondering what are HttpReports adventages over [AppMetrics](https://github.com/AppMetrics/AppMetrics)? 
- Does it have any performance impact on requests
- How big is the impact on the memory?
- Do you plan to add any kind of performance monitoring?
- Do you plan to add monitoring for individual endpoints?
- Do you plan to add support for centralized logging? 
- Do you plan to add support for code profiling? Something like this -> https://stackify.com/retrace-code-profiling/

**Comment by SpringLeee** [comment]
- I think HttpReports can analyze user request information, like request and response, we also have multi-dimensional visual monitoring for api.
- Unfortunately, we haven't done a detailed performance test yet, but we support asynchronous bulk information collection, we also recommend that the user configure it in this way.
- We currently support english documents，and we can support english dashboard as soon as next week.
- The next thing to do is monitor and analysis the CLR , GC... , although it seems a little difficult, hah...
- We currently support monitoring for the entire service node，like timeout, error...,  next we will support user-defined filters，in this way, users can choose the api of interest to analyze.
- We don't have a plan to centralized logs yet.
- Code analysis helps users find problems faster, and means more detailed monitoring，but we don't have a good solution to do this，when the basic functions are finished，we will consider how to implement code analysis

**Comment by mzorec** [comment]
I would definetly like to see that HttpReports supports english dashbord :) 

I think this project has potential and there arent many good open source monitoring libraries so I think HttpReports should join NCC.

**Comment by NMSAzulX** [comment]
@mzorec  I think ElderJames is already doing SkyApm, so wouldn't it be better to add Metrics.NET to the roadmap of this library?

**Comment by alexinea** [comment]
After a period of understanding, I also think that HttpReports is a very potential project, and the HttpReports author can respond to various problems of users in a timely manner.

So I think HttpReports should be eligible to join NCC.

**Comment by ElderJames** [comment]
+1

**Comment by xin-lai** [comment]
+1

**Comment by NMSAzulX** [comment]
+1

**Comment by Ahoo-Wang** [comment]
+1
