### ISSUE TITLE
C#通用代码生成器

### ISSUE THREAD

**Issue by HisKingdom** [dotnetcore/Home#4]

**Comment by liuhaoyang** [comment]
请添加详细的项目描述，开源协议，及使用案例（如果有）。

**Comment by HisKingdom** [comment]
嘿嘿 本来之前是写了的  后来膜拜了下你们写的项目 突然发现有点班门弄斧 就给删了 我还是太年轻~
项目地址：https://github.com/HisKingdom/CodeGenerator
主要是基于abp.zero core5.3.0的代码生成器  但是也可以自己改代码加模板扩展
因为之前写的T4模板在core类库上 用起来遇到了坑 vs扩展开发 看了几天官方文档也没啥头绪
Git上也没找到合适的
所以就自己琢磨加网上查资料写了这么个小工具
目前可以通过反射读取程序集的信息或者读取mysql数据库表结构的方式来生成相应的代码
上榜是不指望上的了  权当抛个砖了
