### ISSUE TITLE
BootstrapBlazor 申请加入

### ISSUE THREAD

**Issue by ArgoZhang** [dotnetcore/Home#46]
名称： BootstrapBlazor
描述：基于 Bootstrap 的 Blazor 企业级组件库，可以在项目中实战的组件库
开源地址：https://github.com/ArgoZhang/BootstrapBlazor
许可证情况：LGPL-3.0
本人是核心作者：Argo Zhang
项目文档：https://www.blazor.zone

**Comment by gmf520** [comment]
这个我在用，挺不错的项目

**Comment by yang-xiaodong** [comment]
Hello,

我搜索了一下，发现了这两个 Bootstrap 的 Blazor 实现：

https://github.com/chanan/BlazorStrap
https://github.com/stsrki/blazorise

我想了解的是，这个项目和这两个有所区别呢，还是说属于同类型的项目，能不能说明一下？

**Comment by alexinea** [comment]
BootstrapBlazor 可以在第三方项目中通过**引用**包的形式使用，因此尽管 BootstrapBlazor 的许可证是 LGPL-3.0，但符合 NCC 对开源许可证的要求。

**Comment by xin-lai** [comment]
支持！

**Comment by ArgoZhang** [comment]
> Hello,
> 
> 我搜索了一下，发现了这两个 Bootstrap 的 Blazor 实现：
> 
> https://github.com/chanan/BlazorStrap
> https://github.com/stsrki/blazorise
> 
> 我想了解的是，这个项目和这两个有所区别呢，还是说属于同类型的项目，能不能说明一下？

您好！
您发的这两个链接都是 bootstrap 的  blazor 实现组件库，我从以下几个方面进行一下比较

### 受众基础
`Blazorstrap` 与 `Blazorise` 都是外国友人开源作品，托管于 github.com 平台，国内受众面不大，由于 github.com 国内速度喜人，导致这两个项目的示例网站打开是相等的卡，我试过 30 分钟打不开的尴尬局面，无形中拒绝了一批浏览者，`BootstrapBlazor` 为国人开源作品，分别托管于 github.com 与 gitee.com 平台，演示网站也针对国内与国际分别进行了优化，国内为 https://www.blazor.zone，国际为 https://argozhang.github.io/ 为传播 `Blazor` 技术做了两手准备。大大填补了国人学习 `Blazor` 的空白

### 技术选型不同
`Blazorise` 严格的说并不是为 `Bootstrap` 的实现，它自己使用了一套皮肤机制可以选择 `Bootstrap` `Material` `Bulma` `eFrolic` `AntDesign` 等多套样式

`BlazorStrap`  是 `Bootstrap` 的 `Blazor` 实现库，与 `Bootstrap` 官网高度保持一致

`BootstrapBlazor` 不仅仅是 `Bootstrap` 的实现库，结合了 `Eleme` 与 `AntDesign` 的官方组件库，均以 `Bootstrap` 样式风格实现了大量的组件，目前拥有组件多达 70+，尤其是核心组件 `Table` 是前两个组件组无法比拟的，为使用者大大节约了开发周期与代码量，可查看相关公众号文章 [BootstrapBlazor-Table 介绍](https://mp.weixin.qq.com/s/d2bA_DyalnskZQFiOHApkA)

### 实用效果不同
由于 `BootstrapBlazor` 这套组件宣传非常少，所以知道的人也不多，尤其是提交采用了中文信息提交，导致对国际友人非常不友好，但是在国内还是受到大批粉丝关注，来我群里很多人都说过一句话，**`blazor` 组件库真多，但是用来用去还是得用您这套，确实好用**，群中好多网友都是使用 `Blazorise` `BlazorStrap` `AntDesign` 等开源组件设置付费组件 `Telerik` `DevExpress` `SyncFunsion`，最终都选择使用我这套组件来完成产品的。目前 `BootstrapBlazor` 在码云平台收到 star 数量为 **1915**，相比前面两个国际化的组件库来说 star 数也是比他们多很多的。由于项目采用 `LGPL-3.0` 协议，也是完全可以商用的，群中数个项目都在使用本组件进行项目开发，本人的所有项目均使用这套组件进行开发，并交付客户，所以这套组件不仅仅是一个开源学习的代码库，是完全经得起实战考验的组件库。是将 .net 技术实战化的实践。

### Issue 维护

这套组件 Issue 都是第一时间响应与维护，每天发布 beta 版本，每周五发布正式版本，与前两个项目相比，无论是更新速度，还是质量都要好很多，

- `Blazorise` Issue 数量 251
- `Blazorstrap` Issue 数量 64

感谢大佬们 review

**Comment by 2881099** [comment]
支持！

**Comment by NMSAzulX** [comment]
支持

**Comment by liuliang-wt** [comment]
支持，wtm正打算上blazor

**Comment by xljiulang** [comment]
组件性能不错

**Comment by zhangpeihang0424** [comment]
支持 支持 支持

**Comment by gmf520** [comment]
BootstrapBlazor 确实是相当不错的UI，支持+1

**Comment by geffzhang** [comment]
支持BootstrapBlazor，我也正在使用这套库在项目中使用，对于实际的项目交付很有帮助
