### ISSUE TITLE
AgileConfig申请加入NCC

### ISSUE THREAD

**Issue by kklldog** [dotnetcore/Home#50]
AgileConfig申请加入NCC 。   
AgileConfig是一个基于.net core开发的轻量级配置中心。   
1. 部署简单，最少只需要一个数据节点，支持docker部署
2. 支持多节点分布式部署来保证高可用
3. 配置支持按应用隔离，应用内配置支持分组隔离
4. 应用支持继承，可以把公共配置提取到一个应用然后其它应用继承它
5. 使用长连接技术，配置信息实时推送至客户端
6. 支持IConfiguration，IOptions模式读取配置，原程序几乎可以不用改造
7. 配置修改支持版本记录，随时回滚配置
8. 如果所有节点都故障，客户端支持从本地缓存读取配置

项目主页： https://github.com/kklldog/AgileConfig
作者：minjie.zhou
演示地址：[AgileConfig Server Demo](http://agileconfig.xbaby.xyz:5000)   密码123456   

---

## Additional information

- [x] 1 - The project is based on .NET technology.
- [x] 2 - The project has a clear git commit log.
- [x] 3 - Unit tests with considerable coverage
- [ ] 4 - The project has benchmarking information (for infrastructure projects, this paragraph should be met)
- [x] 5 - The project creation time should be at least three natural months from the application time
- [x] 6 - The core developers of the project team should make effective contributions to the project within one natural month from the application time
- [x] 7 - Project should be hosted on GitHub first
- [x] 8 - The number of stars in the project is not less than 100
- [x] 9 - Project should have more complete information:
  - [x]   §9.1 - README (, with internationalization is better)
  - [x]   §9.2 - Documentation or Wiki
  - [x]   §9.3 - Sample code
  - [ ]   §9.4 - Roadmap
  - [x]   §9.5 - Other options: website, blog, manual, tutorial or publication
- [x] 10 - The project should have more reliable technical support and response capabilities:
  - [x]   §10.1 - More effective issue response
  - [x]   §10.2 - Other options: communities, mail groups, groups and other social media channels, etc.
- [ ] 11 - The project has a clear development plan and roadmap
- [x] 12 - The project has not received sponsorship from commercial companies or organizations, and no company has paid for the project
- [x] 13 - The project has no copyright issues and meets the copyright requirements in the "Community Project Copyright and Open Source License Regulations";

**Comment by alexinea** [comment]
Hi, 感谢你的申请：）  请根据我们的要求填写 Additional Information，我已把模板更新在主贴上了。

**Comment by kklldog** [comment]
@alexinea 
感谢，已补充信息。
