### ISSUE TITLE
silky微服务框架申请加入NCC

### ISSUE THREAD

**Issue by liuhll** [dotnetcore/Home#52]
# Basic

## Project Name:
- silky微服务框架
## Project Address on GitHub (**and** other addresses, such as Gitee or GitLab):
- https://github.com/liuhll/silky
## Project Description:
- lms是一个旨在通过.net平台快速构建微服务开发的框架。具有稳定、安全、高性能、易扩展、使用方便的特点。lms内部通过dotnetty实现高性能的rpc通信,使用zookeeper作为服务注册中心。RPC通信支持随机轮询、哈希一致性、随机路由等负载均衡算法。

## Document, Blog or Wiki address:
- http://docs.silky-fk.com/

## Author:
liuhll

## Development team or main contributors:
liuhll
## License:
MIT
## Additional information

- [x] 1 - The project is based on .NET technology.
- [x] 2 - The project has a clear git commit log.
- [ ] 3 - Unit tests with considerable coverage
- [x] 4 - The project has benchmarking information (for infrastructure projects, this paragraph should be met)
- [x] 5 - The project creation time should be at least three natural months from the application time
- [x] 6 - The core developers of the project team should make effective contributions to the project within one natural month from the application time
- [x] 7 - Project should be hosted on GitHub first
- [x] 8 - The number of stars in the project is not less than 100
- [x] 9 - Project should have more complete information:
  - [x]   §9.1 - README (, with internationalization is better)
  - [x]   §9.2 - Documentation or Wiki
  - [x]   §9.3 - Sample code
  - [x]   §9.4 - Roadmap
  - [x]   §9.5 - Other options: website, blog, manual, tutorial or publication
- [ ] 10 - The project should have more reliable technical support and response capabilities:
  - [ ]   §10.1 - More effective issue response
  - [x]   §10.2 - Other options: communities, mail groups, groups and other social media channels, etc.
- [x] 11 - The project has a clear development plan and roadmap
- [x] 12 - The project has not received sponsorship from commercial companies or organizations, and no company has paid for the project
- [x] 13 - The project has no copyright issues and meets the copyright requirements in the "Community Project Copyright and Open Source License Regulations";

**Comment by alexinea** [comment]
It is a great honor to see the LMS microservice framework.

According to our standards for new projects, we found that LMS has not yet met the requirements of the Standard Review in some cases, such as the number of Stars.

The LMS microservice framework looks very interesting at the moment, and we will continue to pay attention to this project.

(*╹▽╹*)

**Comment by liuhll** [comment]
Thank you for your approval. I will try my best to complete the requirements of the review

**Comment by liuhll** [comment]
@alexinea HI,能帮忙孵化该项目吗?

**Comment by alexinea** [comment]
We are reviewing the Silky project (phase-1 review) and restarting the technical review.
Thank you for your support.

**Comment by alexinea** [comment]
The view of the PMC is that, the microservice framework Silky still needs to provide practical cases at this stage.

Silky is a good framework. We maintain close communication with the authors of the Silky framework.

Looking forward to a better Silky.
