### ISSUE TITLE
BulmaRazor申请加入NCC

### ISSUE THREAD

**Issue by loogn** [dotnetcore/Home#53]
## BulmaRazor 是一套基于 Bulma 和 Blazor 的轻量级组件库

- 项目地址：https://github.com/loogn/bulmarazor

- 官网文档：https://bulmarazor.loogn.net/docs/overview/start

- 作者：lucky7 
-  邮件:   loogn_0707#126.com

- 开源协议：MIT

**Comment by alexinea** [comment]
The project has not been effectively updated in the past three months, so the project has not passed the **Standard Review** for this time. But this does not mean it is the final result. In the future, welcome to join us at any time.  :)
