### ISSUE TITLE
FastGithub加入NCC的申请

### ISSUE THREAD

**Issue by xljiulang** [dotnetcore/Home#54]
### 名称
FastGithub

###描述
github加速神器

### 加入事由
FastGithub在遵循我国法律的提前下，可以从本质上加速github所有相关域名，让开发者丝滑地使用github所有功能。但本人精力有限，希望捐献给社区一起来发扬光大，为开发者造福。

### 项目官档
https://github.com/xljiulang/FastGithub

### 文档或 Wiki 地址
* https://github.com/xljiulang/FastGithub/blob/master/README.md
* https://github.com/xljiulang/FastGithub/blob/master/FastGithub/README.MD
 
### 作者及核心贡献者信息
老九：WebApiClient作者

### 许可证情况
https://github.com/xljiulang/FastGithub/blob/master/LICENSE

#### 单元测试
目前缺失，也没有想到很好的办法进行测试，后期可以考虑对一些关键函数进行单元测试。

**Comment by NMSAzulX** [comment]
正在用着, 感谢老九.  项目可配, 不仅限于 Github, 后期增加后台管理页面, 合法易用, 同意进入组织孵化.

**Comment by zlzforever** [comment]
同意，很有意思的东西

**Comment by alexinea** [comment]
赞同，造福开发人员的好工具。

**Comment by Ahoo-Wang** [comment]
支持！

**Comment by stulzq** [comment]
支持！
