### ISSUE TITLE
BigCookieKit 申请加入

### ISSUE THREAD

**Issue by BigBigZBBing** [dotnetcore/Home#55]
## Basic

Project Name:BigCookieKit

Project Address on GitHub (**and** other addresses, such as Gitee or GitLab):https://github.com/BigBigZBBing/BigCookieKit

Project Description:高性能反射 Office高性能读写

Document, Blog or Wiki address:https://blog.csdn.net/weixin_42995482

Author:Big.Cookie

Development team or main contributors:Big.Cookie

License:MIT

## Additional information

- [x] 1 - The project is based on .NET technology.
- [x] 2 - The project has a clear git commit log.
- [x] 3 - Unit tests with considerable coverage
- [x] 4 - The project has benchmarking information (for infrastructure projects, this paragraph should be met)
- [x] 5 - The project creation time should be at least three natural months from the application time
- [x] 6 - The core developers of the project team should make effective contributions to the project within one natural month from the application time
- [x] 7 - Project should be hosted on GitHub first
- [ ] 8 - The number of stars in the project is not less than 100
- [x] 9 - Project should have more complete information:
  - [x]   §9.1 - README (, with internationalization is better)
  - [ ]   §9.2 - Documentation or Wiki
  - [x]   §9.3 - Sample code
  - [ ]   §9.4 - Roadmap
  - [ ]   §9.5 - Other options: website, blog, manual, tutorial or publication
- [x] 10 - The project should have more reliable technical support and response capabilities:
  - [x]   §10.1 - More effective issue response
  - [x]   §10.2 - Other options: communities, mail groups, groups and other social media channels, etc.
- [ ] 11 - The project has a clear development plan and roadmap
- [x] 12 - The project has not received sponsorship from commercial companies or organizations, and no company has paid for the project
- [x] 13 - The project has no copyright issues and meets the copyright requirements in the "Community Project Copyright and Open Source License Regulations";

**Comment by alexinea** [comment]
In our Standard Review, we think [BigCookieKit](https://github.com/BigBigZBBing/BigCookieKit) is a good tool, but it has not yet met the requirements of [Community Project Accession Reg, 2020](https://github.com/dotnetcore/Home/blob/master/docs/rules/community-project-accession-reg-2020.md). According to the norms and procedures of the community review, we suspend the application process of the BigCookieKit project.

頑張ってください ヾ(◍°∇°◍)ﾉﾞ
