### ISSUE TITLE
ShardingCore 申请加入NCC

### ISSUE THREAD

**Issue by xuejmnet** [dotnetcore/Home#56]
[ShardingCore](https://github.com/xuejmnet/sharding-core) 申请加入NCC。
`ShardingCore `一款`ef-core`下高性能、轻量级针对分表分库读写分离的解决方案，具有零依赖、零学习成本、零业务代码入侵。

该库的特点:
 - 支持efcore2、3、5、6版本
 - 针对efcore支持分表、分库、读写分离等功能
 - 具有零依赖、零学习成本、零业务代码入侵
 - 支持所有以efcore作为数据驱动的框架如:AbpVNext
 - 使用流式聚合保证高性能和轻量级,性能表现为:O(n)
 - 支持同库下多表join，目前支持分表和分表，分表和不分表，支持group 聚合函数
 - 支持所有efcore对应版本支持的数据库
 - 提供默认分片路由和手动路由，支持自定义业务路由和自定义动态分表
 - 支持code-first
 - 提供按时间分表(顺序分表)的O(1)性能分页
 - 支持efcore生态下的所有批量插件
 
 项目主页：https://github.com/xuejmnet/sharding-core
文档：https://xuejmnet.github.io/sharding-core-doc/
作者：薛家明
开源协议：Apache-2.0

## Additional information

- [x] 1 - The project is based on .NET technology.
- [x] 2 - The project has a clear git commit log.
- [x] 3 - Unit tests with considerable coverage
- [x] 4 - The project has benchmarking information (for infrastructure projects, this paragraph should be met)
- [x] 5 - The project creation time should be at least three natural months from the application time
- [x] 6 - The core developers of the project team should make effective contributions to the project within one natural month from the application time
- [x] 7 - Project should be hosted on GitHub first
- [x] 8 - The number of stars in the project is not less than 100
- [ ] 9 - Project should have more complete information:
  - [x]   §9.1 - README (, with internationalization is better)
  - [x]   §9.2 - Documentation or Wiki
  - [x]   §9.3 - Sample code
  - [ ]   §9.4 - Roadmap
  - [x]   §9.5 - Other options: website, blog, manual, tutorial or publication
- [x] 10 - The project should have more reliable technical support and response capabilities:
  - [x]   §10.1 - More effective issue response
  - [x]   §10.2 - Other options: communities, mail groups, groups and other social media channels, etc.
- [ ] 11 - The project has a clear development plan and roadmap
- [x] 12 - The project has not received sponsorship from commercial companies or organizations, and no company has paid for the project
- [x] 13 - The project has no copyright issues and meets the copyright requirements in the "Community Project Copyright and Open Source License Regulations";

**Comment by kiler398** [comment]
简单看了一下文档，应该还不错的，支持加入，也希望作者多写一些实际使用场景应用的文章来做推广，如sass系统的自动分库设计。

**Comment by xuejmnet** [comment]
> 简单看了一下文档，应该还不错的，支持加入，也希望作者多写一些实际使用场景应用的文章来做推广，如sass系统的自动分库设计。

谢谢支持，后续肯定会有更多的使用场景

**Comment by kklldog** [comment]
非常不错的一个项目。支持！
就是能不能写点关于原理，实现方式上的介绍，让使用者也好有个数。

**Comment by xuejmnet** [comment]
> 非常不错的一个项目。支持！ 就是能不能写点关于原理，实现方式上的介绍，让使用者也好有个数。

可以的目前博客园有对应的原理,后续会有两个文档一个开发者文档一个使用者文档

**Comment by alexinea** [comment]
技术评审完成，支持进入 NCC
