### ISSUE TITLE
CORE QQ 群: 436035237 已经解散了吗？

### ISSUE THREAD

**Issue by AlphaYu** [dotnetcore/Home#57]
![image](https://user-images.githubusercontent.com/23010680/189168095-bcb74433-045c-438b-90e8-db724f331f4f.png)

**Comment by AlphaYu** [comment]
最次验证了一下，确实不存在这个群。

**Comment by alexinea** [comment]
神奇呀，配置都是对的……难道被腾讯技术处理了 😓

**Comment by alexinea** [comment]
无解，也许真被腾讯技术处理了……先 close issue 先，回头再看……
