### ISSUE TITLE
BotSharp申请加入NCC

### ISSUE THREAD

**Issue by Oceania2018** [dotnetcore/Home#6]
BotSharp 是一款为方便构建智能对话机器人平台而开发的开源框架，最大的特点是所有模型算法都是基于 .NET Core 开发实现。
项目地址：https://github.com/Oceania2018/BotSharp
文档地址：https://botsharp.readthedocs.io

**Comment by zlzforever** [comment]
agree

**Comment by fanliang11** [comment]
赞

**Comment by liuhaoyang** [comment]
+1

**Comment by alexinea** [comment]
+1

**Comment by NMSAzulX** [comment]
+1

**Comment by LyricsYo** [comment]
+1👍

**Comment by xljiulang** [comment]
欢迎

**Comment by stulzq** [comment]
同意

**Comment by kiler398** [comment]
同意

**Comment by zengbin93** [comment]
厉害

**Comment by wangpengxpy** [comment]
同意

**Comment by geffzhang** [comment]
同意

**Comment by yang-xiaodong** [comment]
According to the NCC program accession process, we initiated the vote, and more than 50% of the people agreed to this application, approve to join. 

Congratulations !
