### ISSUE TITLE
EF Core适配国产人大金仓和高斯数据库申请加入NCC

### ISSUE THREAD

**Issue by wangpengxpy** [dotnetcore/Home#61]
ORM框架适配各式数据库百家齐放，但针对官方EF Core适配国产数据库仍比较欠缺，故申请适配目前比较主流的国产数据库！

第一阶段规划：最近一周内完成适配.NET 6.0版本

1、创建2个仓库：KingbaseES和GaussDB

2、人大金仓包名：DotNetCore. EntityFrameworkCore.KingbaseES（适配人大金仓R6版本）

3、高斯数据库包名：DotNetCore.EntityFrameworkCore.GaussDB

二者基于Npgsql适配，故协议采用和Npgsql等同开源协议（PostgreSQL License）！

**Comment by alexinea** [comment]
We welcome the ITAI (Information Technology Application Innovation) project  to be a member project of NCC. Considering the significance of the projects, I think that these two projects meet the requirements of internal incubation projects. Therefore, I agree to join the NCC.

**Comment by liuhaoyang** [comment]
+1

**Comment by NMSAzulX** [comment]
+1

**Comment by yang-xiaodong** [comment]
+1 , Great Job

**Comment by catcherwong** [comment]
+1

**Comment by alexinea** [comment]
Following discussion and voting by the NCC PMC team, the two projects described in this application are approved to enter the NCC community and become "incubation projects". Our community supports China's ITAI (Information Technology Application Innovation) project. And welcome more ITAI projects to join us.

Finally, congratulations, Jeffcky. Thank you, @wangpengxpy .

**Comment by UtilCore** [comment]
+1

**Comment by xyyhqq** [comment]
+1
