### ISSUE TITLE
NCC PMC 关于原 NCC BotSharp 项目退出的通告

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/Home#7]
# 关于原 NCC BotSharp 项目退出的通告

NCC PMC Team 和 .NET Core Community PMC Team 遗憾地向诸位通报，因理念不同、道路差异，原 NCC BotSharp 项目正式退出 .NET Core Community，NCC 和 .NET Core Community 对此表示遗憾，由衷地希望原 NCC BotSharp 项目能继续发展壮大。

经五位 NCC 联合发起人一致授权：
NCC 社区资源管理小组收回 https://projects.dotnet-china.org 对原 NCC BotSharp 项目的索引。
NCC 社区项目管理委员会关闭 NCC BotSharp Team 小组。

NCC 和 .NET Core Community 诚挚欢迎所有优秀项目加入 .NET Core Community，一同为 dotnet 生态的完善展现社区力量、贡献社区智慧。

同时，NCC 决定今日起正式开始改革，完善组织各项规范和流程，并适时通过 https://github.com/dotnetcore/Home 通报改革进展。

**Comment by liuhaoyang** [comment]
很遗憾听到这个消息。祝福BotSharp。
