### ISSUE TITLE
WTM框架申请加入NCC

### ISSUE THREAD

**Issue by liuliang-wt** [dotnetcore/Home#8]
无意中看到这个组织，提交一个试试。 https://github.com/WalkingTec/WalkingTec.Mvvm

WTM框架介绍
WalkingTec.Mvvm框架（简称WTM）最早开发与2013年，基于Asp.net MVC3 和 最早的Entity Framework, 当初主要是为了解决公司内部开发效率低，代码风格不统一的问题。经历了四年间数十个项目的考验，框架逐步的完善，推出了四个主要版本。 2017年9月，我们将代码移植到了.Net Core上，并进行了深度优化和重构，推出了基于Asp.net Core和EF Core的全新框架，新框架在架构，稳定性，速度上都有长足进步，真正成为一款高效开发的利器。

框架文档地址：http://wtmdoc.walkingtec.cn 

由于我们公司的业务关系，WTM框架在联想，中外运，滴滴，每日优鲜等大企业的中小型项目中都有使用，至少有50个成功项目经验

**Comment by liuhaoyang** [comment]
@alexinea

**Comment by alexinea** [comment]
我赞同。

CC 至 @UtilCore

**Comment by wangpengxpy** [comment]
赞同。

**Comment by liuhaoyang** [comment]
@liuliang-wt 能否提供项目的roadmap以供参考？

**Comment by liuliang-wt** [comment]
@liuhaoyang 
框架前后端不分离的模式已经使用了很多年，比较完善了。我们近期的主要目标是三个。
1. 完成前后端分离模式的相关编码，目前前端使用的是React，后续会增加VUE
2. 更加准确智能的代码生成
3. 完善文档

**Comment by kiler398** [comment]
赞同。

**Comment by alexinea** [comment]
@liuliang-wt 你们项目的测试工作一般是如何展开的？

**Comment by UtilCore** [comment]
赞同，欢迎加入NCC

**Comment by liuliang-wt** [comment]
@alexinea  呃。。。测试上比较惭愧，人手不够，没有自动化单元测试，也没有专门的测试人员来测。不过由于公司的业务还算比较多，有很多项目都在使用这个框架，都是实际使用框架的项目里的开发人员给我反馈的bug

**Comment by yang-xiaodong** [comment]
感谢申请加入，非常nice的项目，希望补充一下ut和ci

**Comment by liuliang-wt** [comment]
@yang-xiaodong  ut和ci是我的心病，每次都是在ut和新功能之间选择了新功能。。。我希望加入贵组织的初衷也是看看能不能吸引到志同道合的朋友帮我一起做这个事情。。。

**Comment by liuliang-wt** [comment]
各位老板，我这是通没通过啊。。。

**Comment by fanliang11** [comment]
感谢对于.NET 开源的付出，赞同
